// Dummy sales orders for UI development — will be replaced with Supabase queries
export const DUMMY_SALES_ORDERS = [
  {
    id: 'so-001',
    inventory_stock_id: 1,
    item_id: 1,
    item_name: 'Wireless Mouse',
    item_category: 'Electronics',
    quantity: 5,
    status: 'pending',
    customer_name: 'John Smith',
    customer_contact: 'john@example.com',
    notes: 'Urgent order',
    created_by: 'user-002',
    created_by_name: 'Sales Rep A',
    approved_by: null,
    dispatched_by: null,
    created_at: '2026-03-25T10:30:00Z',
    updated_at: '2026-03-25T10:30:00Z',
  },
  {
    id: 'so-002',
    inventory_stock_id: 2,
    item_id: 2,
    item_name: 'Office Chair',
    item_category: 'Furniture',
    quantity: 2,
    status: 'approved',
    customer_name: 'Jane Doe',
    customer_contact: 'jane@example.com',
    notes: '',
    created_by: 'user-002',
    created_by_name: 'Sales Rep A',
    approved_by: 'user-001',
    approved_by_name: 'Admin User',
    dispatched_by: null,
    created_at: '2026-03-24T14:00:00Z',
    updated_at: '2026-03-25T09:00:00Z',
  },
  {
    id: 'so-003',
    inventory_stock_id: 3,
    item_id: 3,
    item_name: 'Programming Book',
    item_category: 'Books',
    quantity: 10,
    status: 'dispatched',
    customer_name: 'Bob Wilson',
    customer_contact: 'bob@example.com',
    notes: 'Bulk order for training',
    created_by: 'user-002',
    created_by_name: 'Sales Rep A',
    approved_by: 'user-001',
    approved_by_name: 'Admin User',
    dispatched_by: 'user-003',
    dispatched_by_name: 'Dispatcher X',
    created_at: '2026-03-20T08:00:00Z',
    updated_at: '2026-03-22T16:00:00Z',
  },
  {
    id: 'so-004',
    inventory_stock_id: 4,
    item_id: 4,
    item_name: 'Winter Jacket',
    item_category: 'Clothing',
    quantity: 3,
    status: 'rejected',
    customer_name: 'Alice Brown',
    customer_contact: 'alice@example.com',
    notes: 'Out of season',
    created_by: 'user-002',
    created_by_name: 'Sales Rep A',
    approved_by: 'user-001',
    approved_by_name: 'Admin User',
    dispatched_by: null,
    created_at: '2026-03-23T11:00:00Z',
    updated_at: '2026-03-24T10:00:00Z',
  },
  {
    id: 'so-005',
    inventory_stock_id: 5,
    item_id: 1,
    item_name: 'Bluetooth Keyboard',
    item_category: 'Electronics',
    quantity: 8,
    status: 'pending',
    customer_name: 'Charlie Green',
    customer_contact: 'charlie@example.com',
    notes: '',
    created_by: 'user-002',
    created_by_name: 'Sales Rep B',
    approved_by: null,
    dispatched_by: null,
    created_at: '2026-03-26T09:15:00Z',
    updated_at: '2026-03-26T09:15:00Z',
  },
]
